#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("frankensteinsmonster.Resource", IsApplication=true)]

namespace frankensteinsmonster
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050031
			public const int Enigma_Button = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int HillCipherButton = 2131034160;
			
			// aapt resource value: 0x7f05002e
			public const int RSA = 2131034158;
			
			// aapt resource value: 0x7f05002a
			public const int askDecrypt = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int askInverse = 2131034150;
			
			// aapt resource value: 0x7f050047
			public const int baseTenBlock = 2131034183;
			
			// aapt resource value: 0x7f050055
			public const int baseTwentySeven = 2131034197;
			
			// aapt resource value: 0x7f050044
			public const int blockSize = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int block_size_prompt = 2131034179;
			
			// aapt resource value: 0x7f050034
			public const int chooseMatrix = 2131034164;
			
			// aapt resource value: 0x7f050046
			public const int conv_ten_prompt = 2131034182;
			
			// aapt resource value: 0x7f05003f
			public const int decryptButton = 2131034175;
			
			// aapt resource value: 0x7f050054
			public const int enc_27_prompt = 2131034196;
			
			// aapt resource value: 0x7f05004c
			public const int enc_block_prompt = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int encryptBlock1 = 2131034189;
			
			// aapt resource value: 0x7f05003e
			public const int encryptButton = 2131034174;
			
			// aapt resource value: 0x7f050022
			public const int encryptHill = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int encryptHillMessage = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int encryptHillTry = 2131034147;
			
			// aapt resource value: 0x7f050038
			public const int encryptMessage = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int encryptStep = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int encryptTry = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int encryptionView = 2131034173;
			
			// aapt resource value: 0x7f050001
			public const int error_space = 2131034113;
			
			// aapt resource value: 0x7f050027
			public const int hillInverse = 2131034151;
			
			// aapt resource value: 0x7f05001b
			public const int hillMatrix = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int hillMatrixMessage = 2131034138;
			
			// aapt resource value: 0x7f05001e
			public const int hillMessage = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int hillMessageUser = 2131034143;
			
			// aapt resource value: 0x7f050010
			public const int line1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int line2 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int line3 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int line4 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int line5 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int line6 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int line7 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int line8 = 2131034135;
			
			// aapt resource value: 0x7f05002f
			public const int matrix = 2131034159;
			
			// aapt resource value: 0x7f05001c
			public const int matrixButton = 2131034140;
			
			// aapt resource value: 0x7f050033
			public const int matrixChoice = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int matrixMessage = 2131034162;
			
			// aapt resource value: 0x7f050035
			public const int matrixView = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int messageMessage = 2131034166;
			
			// aapt resource value: 0x7f050002
			public const int messageTag = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int messageText = 2131034115;
			
			// aapt resource value: 0x7f050037
			public const int messageUser = 2131034167;
			
			// aapt resource value: 0x7f050039
			public const int messageView = 2131034169;
			
			// aapt resource value: 0x7f05000c
			public const int message_restate = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int message_restate_txt = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int new_message = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int new_message_txt = 2131034125;
			
			// aapt resource value: 0x7f050053
			public const int out_block_error = 2131034195;
			
			// aapt resource value: 0x7f050050
			public const int out_block_prompt = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int outputBlockSize = 2131034193;
			
			// aapt resource value: 0x7f05004b
			public const int priKey = 2131034187;
			
			// aapt resource value: 0x7f05004a
			public const int pri_key_prompt = 2131034186;
			
			// aapt resource value: 0x7f050042
			public const int pubKey = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int pub_key_prompt = 2131034177;
			
			// aapt resource value: 0x7f050019
			public const int reflect_out = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int reflect_out_prompt = 2131034136;
			
			// aapt resource value: 0x7f050009
			public const int reflect_pairs = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int reflect_prompt = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int resetBttn = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int rotor_order = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int rotor_prompt = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int rotor_tag = 2131034127;
			
			// aapt resource value: 0x7f05002d
			public const int showDecrypt = 2131034157;
			
			// aapt resource value: 0x7f050029
			public const int showInverse = 2131034153;
			
			// aapt resource value: 0x7f05001d
			public const int showMatrix = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int showMessage = 2131034145;
			
			// aapt resource value: 0x7f05002c
			public const int startDecrypt = 2131034156;
			
			// aapt resource value: 0x7f05000a
			public const int submitButton = 2131034122;
			
			// aapt resource value: 0x7f050045
			public const int submitButton1 = 2131034181;
			
			// aapt resource value: 0x7f05004e
			public const int submitButton2 = 2131034190;
			
			// aapt resource value: 0x7f050056
			public const int submitButton3 = 2131034198;
			
			// aapt resource value: 0x7f050048
			public const int submitButton_new = 2131034184;
			
			// aapt resource value: 0x7f050052
			public const int submitButton_out = 2131034194;
			
			// aapt resource value: 0x7f050028
			public const int submitInverse = 2131034152;
			
			// aapt resource value: 0x7f050049
			public const int tenBlocks = 2131034185;
			
			// aapt resource value: 0x7f05004f
			public const int tenEncBlocks = 2131034191;
			
			// aapt resource value: 0x7f050024
			public const int testHill = 2131034148;
			
			// aapt resource value: 0x7f05003c
			public const int testUser = 2131034172;
			
			// aapt resource value: 0x7f050040
			public const int textView1 = 2131034176;
			
			// aapt resource value: 0x7f050007
			public const int top_letter = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int top_prompt = 2131034118;
			
			// aapt resource value: 0x7f050057
			public const int twentySevenBlocks = 2131034199;
			
			// aapt resource value: 0x7f05002b
			public const int userDecrypt = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int viewHillTry = 2131034149;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Enigma_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HillCipher_Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Matrix_Layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RSA_Layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
